"""
These tests are the required check on your pull requests.
They fail until you implement the Phase 1 and Phase 2 functions.
Do not edit this file.
"""
import csv
import pathlib
import pytest

from ingest.loader import read_rows, validate

DATA = pathlib.Path(__file__).parent.parent / "data" / "orders.csv"


def test_read_rows_returns_dicts():
    rows = list(read_rows(DATA))
    assert len(rows) == 209, "expected 209 data rows"
    assert isinstance(rows[0], dict)
    assert rows[0]["status"] == "placed"


def test_validate_accepts_a_good_row():
    ok, reason = validate({
        "order_id": "1", "customer_id": "5", "drink_id": "3", "store_id": "2",
        "qty": "1", "ordered_at": "2026-03-04T09:00:00+05:30", "status": "placed",
    })
    assert ok is True, f"good row rejected: {reason}"


@pytest.mark.parametrize("field,value", [
    ("qty", "0"), ("qty", "-2"), ("qty", "two"),
    ("ordered_at", "not-a-date"), ("status", "exploded"), ("customer_id", ""),
])
def test_validate_rejects_bad_rows(field, value):
    row = {
        "order_id": "1", "customer_id": "5", "drink_id": "3", "store_id": "2",
        "qty": "1", "ordered_at": "2026-03-04T09:00:00+05:30", "status": "placed",
    }
    row[field] = value
    ok, reason = validate(row)
    assert ok is False, f"{field}={value!r} should have been rejected"
    assert reason, "a rejection must come with a reason"
